export const fullName = {
  AUD: 'Australian Dollar',
  BGN: 'Bulgarian Lev',
  BRL: 'Brazilian Real',
  CAD: 'Canadian Dollar',
  CHF: 'Swiss Franc',
  CNY: 'Yuan Renminbi (China)',
  CZK: 'Czech Koruna',
  DKK: 'Denmark Krone',
  EUR: 'Euro',
  GBP: 'British Pound',
  HKD: 'Hong Kong Dollar',
  HRK: 'Croatia Kuna',
  HUF: 'Hungary Forint',
  IDR: 'Indonesia Rupiah',
  ILS: 'Israel New Shekel',
  INR: 'India Rupee',
  ISK: 'Iceland Krona',
  JPY: 'Japan Yen',
  KRW: 'South Korea Won',
  MXN: 'Mexico Peso',
  MYR: 'Malaysia Ringgit',
  NOK: 'Norway Kroner',
  NZD: 'New Zealand Dollar',
  PHP: 'Philippines Peso',
  PLN: 'Poland Zloty',
  RON: 'Romania New Lei',
  RUB: 'Russia Rouble',
  SEK: 'Sweden Krona',
  SGD: 'Singapore Dollar',
  THB: 'Thailand Baht',
  TRY: 'Turkish New Lira',
  USD: 'US Dollar',
  ZAR: 'South Africa Rand'
};
